const fallbackPriceTable = {
  'Rice (Paddy)': { price: 2450, markets: [{ name: 'Bhandara APMC', district: 'Bhandara' }, { name: 'Gondia APMC', district: 'Gondia' }, { name: 'Chandrapur APMC', district: 'Chandrapur' }] },
  'Wheat': { price: 2480, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nagpur APMC', district: 'Nagpur' }, { name: 'Jalgaon APMC', district: 'Jalgaon' }] },
  'Bajra (Pearl Millet)': { price: 2180, markets: [{ name: 'Ahmednagar APMC', district: 'Ahmednagar' }, { name: 'Solapur APMC', district: 'Solapur' }, { name: 'Pune APMC', district: 'Pune' }] },
  'Jowar (Sorghum)': { price: 2800, markets: [{ name: 'Latur APMC', district: 'Latur' }, { name: 'Solapur APMC', district: 'Solapur' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Maize': { price: 2050, markets: [{ name: 'Nashik APMC', district: 'Nashik' }, { name: 'Jalgaon APMC', district: 'Jalgaon' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Ragi (Finger Millet)': { price: 3200, markets: [{ name: 'Thane APMC', district: 'Thane' }, { name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }] },
  'Tur / Arhar (Pigeon Pea)': { price: 9500, markets: [{ name: 'Latur APMC', district: 'Latur' }, { name: 'Akola APMC', district: 'Akola' }, { name: 'Amravati APMC', district: 'Amravati' }] },
  'Gram / Chana (Chickpea)': { price: 5600, markets: [{ name: 'Latur APMC', district: 'Latur' }, { name: 'Jalna APMC', district: 'Jalna' }, { name: 'Nanded APMC', district: 'Nanded' }] },
  'Bengal Gram (Kabuli Chana)': { price: 7800, markets: [{ name: 'Latur APMC', district: 'Latur' }, { name: 'Nagpur APMC', district: 'Nagpur' }, { name: 'Akola APMC', district: 'Akola' }] },
  'Moong (Green Gram)': { price: 7200, markets: [{ name: 'Akola APMC', district: 'Akola' }, { name: 'Amravati APMC', district: 'Amravati' }, { name: 'Washim APMC', district: 'Washim' }] },
  'Urad (Black Gram)': { price: 7800, markets: [{ name: 'Akola APMC', district: 'Akola' }, { name: 'Washim APMC', district: 'Washim' }, { name: 'Buldhana APMC', district: 'Buldhana' }] },
  'Matki (Moth Bean)': { price: 5400, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Solapur APMC', district: 'Solapur' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Lentil (Masoor)': { price: 6300, markets: [{ name: 'Nagpur APMC', district: 'Nagpur' }, { name: 'Wardha APMC', district: 'Wardha' }, { name: 'Amravati APMC', district: 'Amravati' }] },
  'Field Pea (Vatana)': { price: 4200, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Satara APMC', district: 'Satara' }] },
  'Soybean': { price: 4350, markets: [{ name: 'Latur APMC', district: 'Latur' }, { name: 'Akola APMC', district: 'Akola' }, { name: 'Amravati APMC', district: 'Amravati' }] },
  'Cotton (Kapas)': { price: 7200, markets: [{ name: 'Akola APMC', district: 'Akola' }, { name: 'Yavatmal APMC', district: 'Yavatmal' }, { name: 'Jalna APMC', district: 'Jalna' }] },
  'Groundnut (Peanut)': { price: 6100, markets: [{ name: 'Dhule APMC', district: 'Dhule' }, { name: 'Jalgaon APMC', district: 'Jalgaon' }, { name: 'Nandurbar APMC', district: 'Nandurbar' }] },
  'Sesame (Til)': { price: 11500, markets: [{ name: 'Latur APMC', district: 'Latur' }, { name: 'Nanded APMC', district: 'Nanded' }, { name: 'Parbhani APMC', district: 'Parbhani' }] },
  'Sunflower': { price: 5800, markets: [{ name: 'Latur APMC', district: 'Latur' }, { name: 'Solapur APMC', district: 'Solapur' }, { name: 'Osmanabad APMC', district: 'Osmanabad' }] },
  'Mustard': { price: 5600, markets: [{ name: 'Dhule APMC', district: 'Dhule' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Jalgaon APMC', district: 'Jalgaon' }] },
  'Safflower (Kardi)': { price: 5900, markets: [{ name: 'Solapur APMC', district: 'Solapur' }, { name: 'Latur APMC', district: 'Latur' }, { name: 'Osmanabad APMC', district: 'Osmanabad' }] },
  'Castor': { price: 6400, markets: [{ name: 'Jalgaon APMC', district: 'Jalgaon' }, { name: 'Dhule APMC', district: 'Dhule' }, { name: 'Buldhana APMC', district: 'Buldhana' }] },
  'Niger Seed (Ramtil)': { price: 8200, markets: [{ name: 'Gadchiroli APMC', district: 'Gadchiroli' }, { name: 'Chandrapur APMC', district: 'Chandrapur' }, { name: 'Gondia APMC', district: 'Gondia' }] },
  'Linseed': { price: 6800, markets: [{ name: 'Nagpur APMC', district: 'Nagpur' }, { name: 'Wardha APMC', district: 'Wardha' }, { name: 'Amravati APMC', district: 'Amravati' }] },
  'Guar (Cluster Bean)': { price: 5200, markets: [{ name: 'Jalgaon APMC', district: 'Jalgaon' }, { name: 'Dhule APMC', district: 'Dhule' }, { name: 'Nandurbar APMC', district: 'Nandurbar' }] },
  'Onion': { price: 1650, markets: [{ name: 'Lasalgaon APMC', district: 'Nashik' }, { name: 'Pimpalgaon APMC', district: 'Nashik' }, { name: 'Solapur APMC', district: 'Solapur' }] },
  'Tomato': { price: 1400, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Narayangaon APMC', district: 'Pune' }] },
  'Green Chili': { price: 2600, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Solapur APMC', district: 'Solapur' }] },
  'Brinjal (Eggplant)': { price: 1500, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Okra (Bhindi)': { price: 1900, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Solapur APMC', district: 'Solapur' }] },
  'Potato': { price: 1350, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Satara APMC', district: 'Satara' }] },
  'Garlic': { price: 8500, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }, { name: 'Nashik APMC', district: 'Nashik' }] },
  'Ginger': { price: 5200, markets: [{ name: 'Satara APMC', district: 'Satara' }, { name: 'Pune APMC', district: 'Pune' }, { name: 'Kolhapur APMC', district: 'Kolhapur' }] },
  'Turmeric (Halad)': { price: 9800, markets: [{ name: 'Sangli APMC', district: 'Sangli' }, { name: 'Hingoli APMC', district: 'Hingoli' }, { name: 'Nanded APMC', district: 'Nanded' }] },
  'Cabbage': { price: 1100, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Satara APMC', district: 'Satara' }] },
  'Cauliflower': { price: 1400, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Cucumber': { price: 1200, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Solapur APMC', district: 'Solapur' }] },
  'Radish': { price: 1050, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Satara APMC', district: 'Satara' }] },
  'Carrot': { price: 1600, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Satara APMC', district: 'Satara' }] },
  'Beetroot': { price: 1800, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Satara APMC', district: 'Satara' }] },
  'Spinach (Palak)': { price: 1300, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Thane APMC', district: 'Thane' }] },
  'Fenugreek (Methi)': { price: 1700, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Coriander (Dhania)': { price: 2200, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Solapur APMC', district: 'Solapur' }] },
  'Cumin (Jeera)': { price: 24500, markets: [{ name: 'Jalgaon APMC', district: 'Jalgaon' }, { name: 'Dhule APMC', district: 'Dhule' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Fennel (Sauf)': { price: 11200, markets: [{ name: 'Jalgaon APMC', district: 'Jalgaon' }, { name: 'Dhule APMC', district: 'Dhule' }, { name: 'Nashik APMC', district: 'Nashik' }] },
  'Watermelon': { price: 900, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Solapur APMC', district: 'Solapur' }, { name: 'Nashik APMC', district: 'Nashik' }] },
  'Muskmelon': { price: 1100, markets: [{ name: 'Pune APMC', district: 'Pune' }, { name: 'Solapur APMC', district: 'Solapur' }, { name: 'Nashik APMC', district: 'Nashik' }] },
  'Banana': { price: 1450, markets: [{ name: 'Jalgaon APMC', district: 'Jalgaon' }, { name: 'Raver APMC', district: 'Jalgaon' }, { name: 'Nashik APMC', district: 'Nashik' }] },
  'Grapes': { price: 4200, markets: [{ name: 'Nashik APMC', district: 'Nashik' }, { name: 'Sangli APMC', district: 'Sangli' }, { name: 'Pune APMC', district: 'Pune' }] },
  'Pomegranate': { price: 7800, markets: [{ name: 'Solapur APMC', district: 'Solapur' }, { name: 'Nashik APMC', district: 'Nashik' }, { name: 'Ahmednagar APMC', district: 'Ahmednagar' }] },
  'Chikoo (Sapota)': { price: 2400, markets: [{ name: 'Thane APMC', district: 'Thane' }, { name: 'Palghar APMC', district: 'Palghar' }, { name: 'Dahanu APMC', district: 'Palghar' }] },
  'Sugarcane': { price: 315, markets: [{ name: 'Kolhapur Sugar Mills', district: 'Kolhapur' }, { name: 'Ahmednagar Sugar Mills', district: 'Ahmednagar' }, { name: 'Satara Sugar Mills', district: 'Satara' }] },
};

function getFallbackMarkets(cropName) {
  const entry = fallbackPriceTable[cropName];
  if (!entry) return [];
  return entry.markets.map((m, i) => ({
    name: m.name,
    district: m.district,
    date: new Date().toISOString().slice(0, 10),
    price: Math.round(entry.price * (1 + (i - 1) * 0.04)),
    minPrice: Math.round(entry.price * 0.92),
    maxPrice: Math.round(entry.price * 1.08),
  }));
}

module.exports = { getFallbackMarkets };